FROM python:3.11.5-alpine

WORKDIR /app

COPY ./requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

EXPOSE 3000

CMD ["uvicorn", "main:app", "--host" , "0.0.0.0", "--port" , "3000", "--reload"]
