version: "3.2"

services:
  facturas-api:
    image: enzost4/facturas-api:0.0.1
    build:
      context: ./backend/api/
    environment:
      - DATABASE_URL=postgres://postgres:foobarbaz@database:5433/postgres
    networks:
      - facturas-backend-net
      - facturas-frontend-net
    ports:
      - 8080:3000
    restart: unless-stopped
    depends_on:
      - database
    volumes:
      - type: bind
        source: ./backend/api
        target: /app
      - type: volume
        target: /app/venv
      - type: volume
        target: /app/__pycache__

  facturas-frontend:
    image: enzost4/facturas:frontend-0
    build:
      context: ./facturas-frontend
    ports:
      - 5173:5173
    networks:
      - facturas-frontend-net
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./facturas-frontend
        target: /app
      - type: volume
        target: /app/node_modules
    depends_on:
      - facturas-api

  database:
    image: postgres:15.1-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=foobarbaz
    networks:
      - facturas-backend-net
    ports:
      - 5433:5432

networks:
  facturas-backend-net:
  facturas-frontend-net:
volumes:
  pgdata:
